### ISSUE TITLE
AWS code currently assumes HBN

### ISSUE THREAD

**Issue by IsaacCrane** [nrdg/tractoscope#18]
This should be changed to allow for other datasets

**Comment by IsaacCrane** [comment]
This is apparently an issue with the HBN participants.tsv file. The site that the AWS links use is in the form of ses-HBNsiteRU. However, the participants.tsv file just states this person's site as RU. For other datasets without the study name in the session id the present code will not work. Relying on the participants.tsv file will not have the desired results for other datasets with the present code.

**Comment by asagilmore** [comment]
This issue has been fixed in the hcp pull request. As hcp is more bids compliant I have modified the datasetLogic.js to work with hcp and other bids compliant datasets and then added a special case for HBN. Once the HCP pull request is merged this issue can be closed.
