### ISSUE TITLE
Add tract profile view

### ISSUE THREAD

**Issue by arokem** [nrdg/tractoscope#50]
Add another panel that has line plots of tract profiles for the different bundles, similar to the current html output for pyAFQ. Possibly allow selection of metrics from the CSV file, in addition to selection of bundles. How to find this file may also need to be a configurable thing.

This feature should be implemented on a version 0.2, after we have a fully functioning 0.1 that does everything we want it to do for the anatomical (bundle/volume) view.

**Comment by asagilmore** [comment]
This issue has been fixed in the aws-pinia pull request, one that is merged, this issue can be closed.
