### ISSUE TITLE
Change the slice plane color

### ISSUE THREAD

**Issue by arokem** [nrdg/tractoscope#59]
Is it possible to change the color of the slice plane in the 3D view? It's currently purple, but that looks exactly like the color of the left ILF, so that's annoying. Maybe this could be set to white? I don't know whether it's configurable.

**Comment by asagilmore** [comment]
I have fixed this in the aws pull request, so once that it merged we can close this issue. We can make this clip plane grey, which shouldn't interfere with any tract colors, or we can remove it entirely. Let me know which you prefer. Currently it is set to grey in the aws branch.

<img width="769" alt="Screenshot 2023-10-24 at 12 31 28 PM" src="https://github.com/nrdg/tractoscope/assets/54863917/2ff3dde7-b12c-4378-b904-4ecf88caab27">
<img width="769" alt="Screenshot 2023-10-24 at 12 32 08 PM" src="https://github.com/nrdg/tractoscope/assets/54863917/3cc82e7e-16cd-482f-8f5e-448661d80757">

**Comment by arokem** [comment]
Closed through #60
