### ISSUE TITLE
Volume opacity

### ISSUE THREAD

**Issue by richford** [nrdg/tractoscope#7]
It would be nice to be able to adjust the opacity of the brain volume so that you can see the bundles underneath them.

**Comment by neurolabusc** [comment]
See [demo included with issue 598](https://github.com/niivue/niivue/issues/598) for a possible solution as well as caveats.

**Comment by arokem** [comment]
This doesn't work for now, but with the default implemented in #49, in which a three-plane view is provided in addition to the 3D viewer, it also may not be as necessary. Closing until further notice.

**Comment by neurolabusc** [comment]
@arokem this [live demo](https://niivue.github.io/niivue/features/tracts2.html) shows provides a slider named `MeshXRay` that illustrates how to use this function using the current version of NiiVue.

You may also be interested in [the experimental intersecting slice view](https://github.com/niivue/niivue/issues/679).
